const PARTY_MEMBERS = {
    RILLYBOSS: "RillyBoss",
    STEALYBOSS: "RillyBoss2",
    HEALYBOSS: "HealyBoss",
    DEALYBOSS: "DealyBoss",
    MELEEBOSS: "MeleeBoss"
};

const HEALER = PARTY_MEMBERS.HEALYBOSS;
const TANK = PARTY_MEMBERS.MELEEBOSS;

const STATES = {
    PAUSED: 'PAUSED',
    INITIAL_STATE: 'INITIAL STATE',
    ATTACKING: 'ATTACKING',
    MOVING_TO_POTIONS: 'MOVING TO POTIONS',
    BUYING_POTIONS: 'BUYING POTIONS',
    MOVING_TO_ENEMIES: 'MOVING TO ENEMIES'
};

const COMMAND_TYPES = {
    SAY: 'SAY',
    HEAL_REQUEST: 'HEAL_REQUEST'
};

const POTION_TYPES = {
    HP_POTION_SMALL: "hpot0",
    HP_POTION_LARGE: "hpot1",
    MP_POTION_SMALL: "mpot0",
    MP_POTION_LARGE: "mpot1",
}
